# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13messages/test.proto\x12\x08tutorial\"\xb8\x01\n\x10ImageAcquisition\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12<\n\x0c\x63\x61mera_specs\x18\x02 \x01(\x0b\x32&.tutorial.ImageAcquisition.CameraSpecs\x12\x16\n\x0eimage_location\x18\x03 \x02(\t\x1a;\n\x0b\x43\x61meraSpecs\x12\x15\n\rcamera_spec_1\x18\x01 \x01(\t\x12\x15\n\rcamera_spec_2\x18\x02 \x01(\x05'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'messages.test_pb2', globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _IMAGEACQUISITION._serialized_start = 34
    _IMAGEACQUISITION._serialized_end = 218
    _IMAGEACQUISITION_CAMERASPECS._serialized_start = 159
    _IMAGEACQUISITION_CAMERASPECS._serialized_end = 218
# @@protoc_insertion_point(module_scope)
