services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-1
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - rabbitnet
  
  image_acquisition:
    build:
      context: ./
      dockerfile: image_acquisition/Dockerfile
    container_name: image_acquisition
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitnet
    user: root

  model_inference:
    build:
      context: ./
      dockerfile: model_inference/Dockerfile
    container_name: model_inference
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitnet
    user: root
  
  comms:
    build:
      context: ./
      dockerfile: comms/Dockerfile
    container_name: comms
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitnet
    user: root

networks:
  rabbitnet:
    driver: bridge
